using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Microsoft.Win32;
using MarineEnvironment.Models;

namespace MarineEnvironment.Viewer
{
    public partial class MainWindow : Window
    {
        private readonly MarineEnvironmentManager _manager = new MarineEnvironmentManager();
        private GridResult? _currentGrid;
        private SourceState? _selectedSource;
        private double _zoom=1.0,_panX,_panY; private bool _isPanning,_dragMoved; private Point _panStart,_panOrigin;
        private const double MinZoom=1.0,MaxZoom=32.0,ZoomStep=1.25;
        public MainWindow(){InitializeComponent();Closed+=(_,_)=>_manager.Dispose();}
        private void BrowseConfig_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="MarineEnvironment config (*.json)|*.json|All files (*.*)|*.*",CheckFileExists=true};if(d.ShowDialog(this)==true)ConfigPathTextBox.Text=d.FileName;}
        private void LoadConfig_Click(object s,RoutedEventArgs e){try{var p=ConfigPathTextBox.Text.Trim();if(string.IsNullOrWhiteSpace(p)){MessageBox.Show(this,"Select marineenvironment.json first.");return;}var r=_manager.Initialize(p);SourceListBox.ItemsSource=r.Sources;SourceListBox.SelectedItem=r.Sources.FirstOrDefault(x=>x.Status==SourceStatus.Ready)??r.Sources.FirstOrDefault();StatusText.Text=$"Configuration loaded. {r.Sources.Count} source(s), {r.Sources.Count(x=>x.Status==SourceStatus.Ready)} READY.";}catch(Exception ex){MessageBox.Show(this,ex.Message,"Configuration error",MessageBoxButton.OK,MessageBoxImage.Error);}}
        private void SourceListBox_SelectionChanged(object s,SelectionChangedEventArgs e){_selectedSource=SourceListBox.SelectedItem as SourceState;if(_selectedSource==null){SelectedSourceStatusText.Text="";return;}var resolutionNote=_selectedSource.Type==EnvironmentType.Seabed?"\nResolution: vector polygons; Width/Height controls display rasterization.":"\nResolution: Source Native is the default render mode for gridded sources.";SelectedSourceStatusText.Text=$"{_selectedSource.Type} / {_selectedSource.Status}"+(string.IsNullOrWhiteSpace(_selectedSource.Message)?"":$"\n{_selectedSource.Message}")+resolutionNote;}
        private async void Render_Click(object s,RoutedEventArgs e){if(_selectedSource==null||_selectedSource.Status!=SourceStatus.Ready){MessageBox.Show(this,"Select a READY source first.");return;}if(!TryReadDouble(MinLatTextBox,out var a)||!TryReadDouble(MaxLatTextBox,out var b)||!TryReadDouble(MinLonTextBox,out var c)||!TryReadDouble(MaxLonTextBox,out var d)||!TryReadInt(GridWidthTextBox,out var w)||!TryReadInt(GridHeightTextBox,out var h)){MessageBox.Show(this,"Check view bounds and custom/display raster size.");return;}double? depth=null;if(!string.IsNullOrWhiteSpace(DepthTextBox.Text)){if(!TryReadDouble(DepthTextBox,out var dp)){MessageBox.Show(this,"Depth must be numeric or blank.");return;}depth=dp;}var month=Math.Clamp(MonthComboBox.SelectedIndex+1,1,12);var resolutionMode=RenderResolutionComboBox.SelectedIndex==0?GridResolutionMode.SourceNative:GridResolutionMode.Custom;var q=new GridQuery{MinLatitude=a,MaxLatitude=b,MinLongitude=c,MaxLongitude=d,Depth=depth,DateTime=new DateTime(DateTime.Now.Year,month,15,12,0,0),Width=w,Height=h,ResolutionMode=resolutionMode};try{RenderButton.IsEnabled=false;Mouse.OverrideCursor=Cursors.Wait;var g=await Task.Run(()=>_manager.QueryGrid(_selectedSource.Id,q));if(g.Width<1||g.Height<1)throw new InvalidOperationException("The requested view does not intersect any renderable source cells.");_currentGrid=g;MapImage.Source=CreateBitmap(g);EmptyMapText.Visibility=Visibility.Collapsed;MapTitleText.Text=$"{g.SourceId} / {g.Type}";RangeText.Text=g.Type==EnvironmentType.Seabed?"SHOM categorical sediment / official legend colors":!g.Minimum.HasValue||!g.Maximum.HasValue?"No valid values":$"Min {FormatValue(g.Minimum)} | Max {FormatValue(g.Maximum)} {g.Unit}";ResolutionText.Text=BuildResolutionText(g,resolutionMode);PointResultsPanel.Visibility=Visibility.Collapsed;ResetMapTransform();ScaleBarPanel.Visibility=Visibility.Visible;UpdateScaleBar();StatusText.Text=$"Rendered {g.Width} x {g.Height} samples ({EffectiveResolutionMode(g,resolutionMode)}).";}catch(Exception ex){MessageBox.Show(this,ex.ToString(),"Render error",MessageBoxButton.OK,MessageBoxImage.Error);}finally{Mouse.OverrideCursor=null;RenderButton.IsEnabled=true;}}
        private void ZoomIn_Click(object s,RoutedEventArgs e)=>ZoomAt(new Point(MapViewport.ActualWidth/2,MapViewport.ActualHeight/2),ZoomStep); private void ZoomOut_Click(object s,RoutedEventArgs e)=>ZoomAt(new Point(MapViewport.ActualWidth/2,MapViewport.ActualHeight/2),1/ZoomStep); private void ResetZoom_Click(object s,RoutedEventArgs e)=>ResetMapTransform();
        private void MapViewport_MouseWheel(object s,MouseWheelEventArgs e){if(_currentGrid==null)return;ZoomAt(e.GetPosition(MapViewport),e.Delta>0?ZoomStep:1/ZoomStep);e.Handled=true;}
        private void MapViewport_MouseLeftButtonDown(object s,MouseButtonEventArgs e){if(_currentGrid==null)return;_isPanning=true;_dragMoved=false;_panStart=e.GetPosition(MapViewport);_panOrigin=new Point(_panX,_panY);MapViewport.CaptureMouse();MapViewport.Cursor=Cursors.SizeAll;e.Handled=true;}
        private async void MapViewport_MouseLeftButtonUp(object s,MouseButtonEventArgs e){if(!_isPanning)return;var p=e.GetPosition(MapViewport);_isPanning=false;MapViewport.ReleaseMouseCapture();MapViewport.Cursor=Cursors.Arrow;if(!_dragMoved)await QueryAllSourcesAtViewportPosition(p);e.Handled=true;}
        private void MapViewport_MouseMove(object s,MouseEventArgs e){if(_currentGrid==null)return;var p=e.GetPosition(MapViewport);if(_isPanning&&e.LeftButton==MouseButtonState.Pressed){var delta=p-_panStart;if(Math.Abs(delta.X)>2||Math.Abs(delta.Y)>2)_dragMoved=true;_panX=_panOrigin.X+delta.X;_panY=_panOrigin.Y+delta.Y;ClampPan();ApplyMapTransform();return;}if(TryGetRasterCellFromViewport(p,out var r,out var c)){var label=_currentGrid.GetLabel(r,c);var value=label??($"{FormatValue(_currentGrid.GetValue(r,c))} {_currentGrid.Unit}".Trim());CursorInfoText.Text=$"Lat: {_currentGrid.Latitudes[r]:0.#####} Lon: {_currentGrid.Longitudes[c]:0.#####} Value: {value}";}else CursorInfoText.Text="Lat: - Lon: - Value: -";}
        private void MapViewport_MouseLeave(object s,MouseEventArgs e){if(!_isPanning)CursorInfoText.Text="Lat: - Lon: - Value: -";} private void MapViewport_SizeChanged(object s,SizeChangedEventArgs e){if(_currentGrid==null)return;ClampPan();ApplyMapTransform();UpdateScaleBar();}
        private void ZoomAt(Point p,double f){if(_currentGrid==null)return;var old=_zoom;var nz=Math.Max(MinZoom,Math.Min(MaxZoom,old*f));if(Math.Abs(nz-old)<1e-12)return;var ix=(p.X-_panX)/old;var iy=(p.Y-_panY)/old;_zoom=nz;_panX=p.X-ix*nz;_panY=p.Y-iy*nz;ClampPan();ApplyMapTransform();UpdateScaleBar();} private void ResetMapTransform(){_zoom=1;_panX=_panY=0;ApplyMapTransform();UpdateScaleBar();}
        private void ClampPan(){var w=MapViewport.ActualWidth;var h=MapViewport.ActualHeight;if(w<=0||h<=0)return;if(_zoom<=1){_panX=_panY=0;return;}_panX=Math.Max(w-w*_zoom,Math.Min(0,_panX));_panY=Math.Max(h-h*_zoom,Math.Min(0,_panY));} private void ApplyMapTransform(){MapTransform.Matrix=new Matrix(_zoom,0,0,_zoom,_panX,_panY);ZoomText.Text=$"{_zoom*100:0}%";}
        private bool TryGetRasterCellFromViewport(Point p,out int row,out int col){row=col=0;if(_currentGrid==null||MapViewport.ActualWidth<=0||MapViewport.ActualHeight<=0)return false;var x=(p.X-_panX)/_zoom;var y=(p.Y-_panY)/_zoom;if(x<0||y<0||x>=MapViewport.ActualWidth||y>=MapViewport.ActualHeight)return false;col=Math.Max(0,Math.Min(_currentGrid.Width-1,(int)(x/MapViewport.ActualWidth*_currentGrid.Width)));row=Math.Max(0,Math.Min(_currentGrid.Height-1,(int)(y/MapViewport.ActualHeight*_currentGrid.Height)));return true;}
        private void UpdateScaleBar(){if(_currentGrid==null||MapViewport.ActualWidth<=0||_currentGrid.Latitudes.Length==0||_currentGrid.Longitudes.Length==0){ScaleBarPanel.Visibility=Visibility.Collapsed;return;}var cy=(MapViewport.ActualHeight/2-_panY)/_zoom;cy=Math.Max(0,Math.Min(MapViewport.ActualHeight-1,cy));var t=cy/Math.Max(1,MapViewport.ActualHeight-1);var lat=Interpolate(_currentGrid.Latitudes[0],_currentGrid.Latitudes[_currentGrid.Latitudes.Length-1],t);var min=_currentGrid.Longitudes.Min();var max=_currentGrid.Longitudes.Max();var across=HaversineKilometers(lat,min,lat,max)/_zoom;if(across<=0)return;var target=Math.Max(70,Math.Min(150,MapViewport.ActualWidth*.18));var nice=NiceDistance(across*target/MapViewport.ActualWidth);ScaleBarLine.Width=Math.Max(35,Math.Min(MapViewport.ActualWidth*.35,MapViewport.ActualWidth*nice/across));ScaleBarText.Text=nice>=1?$"{nice:0.##} km":$"{nice*1000:0} m";ScaleBarPanel.Visibility=Visibility.Visible;}
        private static double NiceDistance(double x){if(x<=0)return 0;var p=Math.Pow(10,Math.Floor(Math.Log10(x)));var n=x/p;return(n>=5?5:n>=2?2:1)*p;} private static double HaversineKilometers(double a,double b,double c,double d){const double R=6371.0088;double r=Math.PI/180,da=(c-a)*r,dl=(d-b)*r;var q=Math.Sin(da/2)*Math.Sin(da/2)+Math.Cos(a*r)*Math.Cos(c*r)*Math.Sin(dl/2)*Math.Sin(dl/2);return 2*R*Math.Asin(Math.Min(1,Math.Sqrt(q)));} private static double Interpolate(double a,double b,double t)=>a+(b-a)*t;
        private static bool TryReadDouble(TextBox box,out double v)=>double.TryParse(box.Text,NumberStyles.Float,CultureInfo.InvariantCulture,out v); private static bool TryReadInt(TextBox box,out int v)=>int.TryParse(box.Text,NumberStyles.Integer,CultureInfo.InvariantCulture,out v)&&v>0; private static string FormatValue(double? v)=>v.HasValue?v.Value.ToString("0.###",CultureInfo.InvariantCulture):"NoData"; private static string FormatObject(object? v)=>v==null?"NoData":v is IFormattable f?f.ToString("0.###",CultureInfo.InvariantCulture)??"NoData":v.ToString()??"NoData";
        private static string BuildResolutionText(GridResult g,GridResolutionMode requestedMode){if(g.Type==EnvironmentType.Seabed)return $"Vector polygon source | Display raster {g.Width} x {g.Height} | Width/Height affect display only";var lat=TryGetMetadataDouble(g,"sourceLatitudeSpacingArcSeconds");var lon=TryGetMetadataDouble(g,"sourceLongitudeSpacingArcSeconds");var source=lat.HasValue&&lon.HasValue?$"Source grid {FormatAngularSpacing(lon.Value)} x {FormatAngularSpacing(lat.Value)}":"Source grid spacing unavailable";return $"{source} | Rendered {g.Width} x {g.Height} | {EffectiveResolutionMode(g,requestedMode)}";}
        private static string EffectiveResolutionMode(GridResult g,GridResolutionMode requestedMode){if(g.Type==EnvironmentType.Seabed)return "DisplayRaster";if(g.Metadata!=null&&g.Metadata.TryGetValue("resolutionMode",out var value)&&value!=null)return value.ToString()??requestedMode.ToString();return requestedMode.ToString();}
        private static double? TryGetMetadataDouble(GridResult g,string key){if(g.Metadata==null||!g.Metadata.TryGetValue(key,out var value)||value==null)return null;try{return Convert.ToDouble(value,CultureInfo.InvariantCulture);}catch{return null;}}
        private static string FormatAngularSpacing(double arcSeconds){if(Math.Abs(arcSeconds-60.0)<0.01)return "1' (60\")";if(arcSeconds>=60)return $"{arcSeconds/60.0:0.###}' ({arcSeconds:0.###}\")";return $"{arcSeconds:0.###}\"";}
        private static BitmapSource CreateBitmap(GridResult g){if(g.Type==EnvironmentType.Seabed)return CreateSeabedBitmap(g);var px=new byte[checked(g.Width*g.Height*4)];var min=g.Minimum??0;var max=g.Maximum??1;var range=Math.Abs(max-min)<1e-12?1:max-min;for(var i=0;i<g.Values.Length;i++){var o=i*4;var value=g.Values[i];if(!value.HasValue||double.IsNaN(value.Value)||double.IsInfinity(value.Value)){px[o]=245;px[o+1]=245;px[o+2]=245;px[o+3]=255;continue;}var t=Math.Max(0,Math.Min(1,(value.Value-min)/range));var rgb=TurboLike(t);px[o]=rgb.b;px[o+1]=rgb.g;px[o+2]=rgb.r;px[o+3]=255;}var bmp=BitmapSource.Create(g.Width,g.Height,96,96,PixelFormats.Bgra32,null,px,g.Width*4);bmp.Freeze();return bmp;}
        private static BitmapSource CreateSeabedBitmap(GridResult g){var px=new byte[checked(g.Width*g.Height*4)];for(var i=0;i<g.Values.Length;i++){var o=i*4;var value=g.Values[i];if(!value.HasValue||!ShomSedimentCatalog.TryGet((int)Math.Round(value.Value),out var sediment)){px[o]=245;px[o+1]=245;px[o+2]=245;px[o+3]=255;continue;}px[o]=sediment.Blue;px[o+1]=sediment.Green;px[o+2]=sediment.Red;px[o+3]=255;}var bmp=BitmapSource.Create(g.Width,g.Height,96,96,PixelFormats.Bgra32,null,px,g.Width*4);bmp.Freeze();return bmp;}
        private static (byte r,byte g,byte b) TurboLike(double t){var stops=new (double t,byte r,byte g,byte b)[]{(0.00,48,18,59),(0.20,50,84,179),(0.40,31,174,174),(0.60,150,214,75),(0.80,249,154,28),(1.00,180,4,38)};for(var i=1;i<stops.Length;i++){if(t>stops[i].t)continue;var a=stops[i-1];var b=stops[i];var u=(t-a.t)/(b.t-a.t);return((byte)Math.Round(a.r+(b.r-a.r)*u),(byte)Math.Round(a.g+(b.g-a.g)*u),(byte)Math.Round(a.b+(b.b-a.b)*u));}var z=stops[stops.Length-1];return(z.r,z.g,z.b);}
    }
}
