<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <AssemblyName>MarineEnvironment.Viewer</AssemblyName>
    <RootNamespace>MarineEnvironment.Viewer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarineEnvironment\MarineEnvironment.csproj" />
  </ItemGroup>

</Project>
